# This file compiled from .travis.yml.in

sudo: false

language: python

python:
  - "3.5.2"

cache:
  pip: true
  directories:
    - node_modules
    - /home/travis/.rvm/gems

install:
  # Install NodeJS
  - nvm install 4.5.0

  # Install Python dependencies
  - python -m pip install --upgrade pip==8.1.1
  - python -m pip install -r requirements3.txt

  # Install Ruby
  - rvm install 2.3.1
  - rvm @global do gem install bundler -v 1.13.1
  - |
    bundler_uninstall=$( rvm @global do gem list ^bundler$ -i -v "!=1.13.1" )
    if [ "$bundler_uninstall" == "true" ]
    then
      rvm @global do gem uninstall bundler -v "!=1.13.1"
    fi
  - rvm use 2.3.1 --default

  # Invoke will get our other dependencies
  - invoke update_dependencies

script:
  - nosetests
